tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "tkengo/highway"
tap "trustdock/tools", "git@github.com:TRUSTDOCK/homebrew-tools.git"
brew "anyenv"
brew "awscli"
brew "pkg-config"
brew "direnv"
brew "gobject-introspection"
brew "harfbuzz"
brew "ffmpeg"
brew "imagemagick@6"
brew "innotop"
brew "jq"
brew "mas"
brew "mysql@5.7", restart_service: true
brew "nginx", restart_service: true
brew "packer"
brew "peco"
brew "redis", restart_service: true
brew "shared-mime-info"
brew "tig"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "zsh-completions"
brew "heroku/brew/heroku"
brew "tkengo/highway/highway"
brew "trustdock/tools/trustdock", args: ["HEAD"]
cask "chromedriver"
cask "clipy"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "insomnia"
cask "iterm2"
cask "kindle"
cask "ngrok"
cask "skype"
cask "slack"
cask "td-agent"
cask "tunnelblick"
cask "visual-studio-code"
cask "wkhtmltopdf"
cask "zoom"
mas "Bear", id: 1091189122
mas "Xcode", id: 497799835
