let s:jetpackfile = '$HOME/.local/share/vim/pack/jetpack/opt/vim-jetpack/plugin/jetpack.vim'
let s:jetpackurl = "https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim"
if !filereadable(s:jetpackfile)
  call system(printf('curl -fsSLo %s --create-dirs %s', s:jetpackfile, s:jetpackurl))
endif

execute 'source' s:jetpackfile

packadd vim-jetpack
call jetpack#begin('$HOME/.local/share/vim')

Jetpack 'tani/vim-jetpack', { 'opt': 1 }
Jetpack 'junegunn/fzf'
Jetpack 'junegunn/fzf.vim'
Jetpack 'jlanzarotta/bufexplorer'
Jetpack 'prabirshrestha/vim-lsp'
Jetpack 'mattn/vim-lsp-settings'
Jetpack 'prabirshrestha/asyncomplete.vim'
Jetpack 'prabirshrestha/asyncomplete-lsp.vim'
Jetpack 'lambdalisue/fern.vim'
Jetpack 'arcticicestudio/nord-vim'
Jetpack 'vim-airline/vim-airline'
Jetpack 'tomtom/tcomment_vim'

" vim-airline {{{
let g:airline_powerline_fonts = 1
let g:airline_left_sep = "\uE0B8"
let g:airline_right_sep = "\uE0BE"
let g:airline_extensions = ['tabline']
" }}}

" vim-ferm {{{
let g:fern#default_hidden=1
" }}}

" nord-vim {{{
colorscheme nord
" }}}

for name in jetpack#names()
  if !jetpack#tap(name)
    call jetpack#sync()
    break
  endif
endfor

call jetpack#end()

syntax on

set number
set ruler
set list
set listchars=tab:>-,trail:-,eol:$,extends:»,precedes:«,nbsp:%
set incsearch
set hlsearch
set wrap
set showmatch
set showmode
set wildmenu
set whichwrap=h,l
set nowrapscan
set ignorecase
set smartcase
set hidden
set history=50
set helplang=en
set mouse=a
set backspace=indent,eol,start
set encoding=utf-8
set fileencodings=utf-8,sjis,euc-jp,iso-2022-jp,latin1
set fileformats=unix,dos,mac
set formatoptions+=mM
set ambiwidth=double
set display+=lastline
set clipboard=unnamed,autoselect
set nobackup
set noswapfile
set viminfo+=n~/.local/state/vim/viminfo
set laststatus=2

" Leaderを\から,に置き換え
let mapleader = ","

" カーソル設定
let &t_SI .= "\e[6 q" " 挿入モードで非点滅のbarカーソル
let &t_EI .= "\e[2 q" " ノーマルモードで非点滅のblockカーソル

" 表示行移動入れ替え
nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k

" コマンドラインウインドウ表示入れ替え
nnoremap qq: <CR>q:
nnoremap qq/ <CR>q/
nnoremap q: <NOP>
nnoremap q/ <NOP>
nnoremap q? <NOP>

" sを無効化
nnoremap s <Nop>

" カレントウインドウの水平分割(:split)
nnoremap ss :<C-u>sp<CR>

" カレントウインドウの垂直分割(:vsplit)
nnoremap sv :<C-u>vs<CR>

" 分割ウインドウ間の移動
nnoremap sj <C-w>j
nnoremap sk <C-w>k
nnoremap sl <C-w>l
nnoremap sh <C-w>h
nnoremap sw <C-w>w

" ファイルの曖昧検索
nnoremap <Leader>f :FZF<CR>

" ファイル全文の曖昧検索
nnoremap <Leader>r :Rg<CR>

" ファイルエクスプローラーのドロワー表示
function! FernToggle()
  if &filetype ==# "fern"
    wincmd p
  else
    Fern . -reveal=% -drawer -width=40<CR>
  endif
endfunction

nnoremap <silent> <Leader>e :call FernToggle()<CR>
